### ISSUE TITLE
Upgrade to Gio 0.5

### ISSUE THREAD

**Issue by inkeliz** [gioui-plugins/gio-plugins#65]
**Is your feature request related to a problem? Please describe.**
Currently, gio-plugins don't support Gio 0.5. 

**Describe the solution you'd like**
Make it compatible.

**Describe alternatives you've considered**
We need to refactor `plugin` package, and rewrite most demonstrations.

**Comment by ddkwork** [comment]
![QQ截图20240406181716](https://github.com/gioui-plugins/gio-plugins/assets/19886504/54062bf9-4bc4-4dc8-b1f9-6fb0322c80eb)
working one

**Comment by ddkwork** [comment]
![QQ截图20240406192808](https://github.com/gioui-plugins/gio-plugins/assets/19886504/0ed3dad2-7e32-4d74-8b53-5c57a0424013)
working 2

**Comment by ddkwork** [comment]
![QQ截图20240406181716](https://github.com/gioui-plugins/gio-plugins/assets/19886504/86f2bee4-117c-42da-aa2f-7c403d454ff5)

**Comment by ddkwork** [comment]
![QQ截图20240406194039](https://github.com/gioui-plugins/gio-plugins/assets/19886504/5e0941ef-313e-45ff-b02f-1bb95850af8d)

**Comment by ddkwork** [comment]
If you want, I will create pr

**Comment by ddkwork** [comment]
see https://github.com/gioui-plugins/gio-plugins/pull/66 need you do more check

**Comment by ddkwork** [comment]
now， gio latest version is 0.6.

**Comment by inkeliz** [comment]
> ![QQ截图20240406192808](https://private-user-images.githubusercontent.com/19886504/320201232-0ed3dad2-7e32-4d74-8b53-5c57a0424013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MjAwNDMsIm5iZiI6MTcxMjkxOTc0MywicGF0aCI6Ii8xOTg4NjUwNC8zMjAyMDEyMzItMGVkM2RhZDItN2UzMi00ZDc0LThiNTMtNWM1N2EwNDI0MDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDExMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkY2RmMTQwZjI5MGEzMTQzMTA0ODQ4MjM5YjA0ODZjYjJhMWFhMTZmNjk4MGFjNTc1ODc3Yzg1OTc0ODJmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mccLe6NgQ4OeYy4nehot3mGxUZWInMzag6RWcdk_x1w) working 2

Does it works? I mean, when you select an image it displays the image?

**Comment by inkeliz** [comment]
I'm porting it to 0.6. However, it requires changes in Gio itself, see https://github.com/gioui/gio/pull/134.
